//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplikacjaKSFD.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AplikacjaKSFD.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Barki_Unoszenie_sztangi_do_klatki_piersiowej_1 {
            get {
                object obj = ResourceManager.GetObject("Barki_Unoszenie_sztangi_do_klatki_piersiowej_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Barki_Unoszenie_sztangi_do_klatki_piersiowej_2 {
            get {
                object obj = ResourceManager.GetObject("Barki_Unoszenie_sztangi_do_klatki_piersiowej_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Barki_Wyciskanie_żołnierskie_hantlami_siedząc_1 {
            get {
                object obj = ResourceManager.GetObject("Barki_Wyciskanie_żołnierskie_hantlami_siedząc_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Barki_Wyciskanie_żołnierskie_hantlami_siedząc_2 {
            get {
                object obj = ResourceManager.GetObject("Barki_Wyciskanie_żołnierskie_hantlami_siedząc_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Barki_Wyciskanie_żołnierskie_sztangą_stojąc_1 {
            get {
                object obj = ResourceManager.GetObject("Barki_Wyciskanie_żołnierskie_sztangą_stojąc_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Barki_Wyciskanie_żołnierskie_sztangą_stojąc_2 {
            get {
                object obj = ResourceManager.GetObject("Barki_Wyciskanie_żołnierskie_sztangą_stojąc_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Barki_Wyciskanie_żołnierskie_sztangą_stojąc_3 {
            get {
                object obj = ResourceManager.GetObject("Barki_Wyciskanie_żołnierskie_sztangą_stojąc_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Barki_Wyciskanie_żołnierskie_sztangą_stojąc_4 {
            get {
                object obj = ResourceManager.GetObject("Barki_Wyciskanie_żołnierskie_sztangą_stojąc_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Barki_Wznosy_hantli_bokiem_1 {
            get {
                object obj = ResourceManager.GetObject("Barki_Wznosy_hantli_bokiem_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Barki_Wznosy_hantli_bokiem_2 {
            get {
                object obj = ResourceManager.GetObject("Barki_Wznosy_hantli_bokiem_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Barki_Wznosy_hantli_przodem_1 {
            get {
                object obj = ResourceManager.GetObject("Barki_Wznosy_hantli_przodem_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Barki_Wznosy_hantli_przodem_2 {
            get {
                object obj = ResourceManager.GetObject("Barki_Wznosy_hantli_przodem_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Barki_Wznosy_hantli_przodem_3 {
            get {
                object obj = ResourceManager.GetObject("Barki_Wznosy_hantli_przodem_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Barki_Wznosy_hantli_tyłem_leżąc_1 {
            get {
                object obj = ResourceManager.GetObject("Barki_Wznosy_hantli_tyłem_leżąc_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Barki_Wznosy_hantli_tyłem_leżąc_2 {
            get {
                object obj = ResourceManager.GetObject("Barki_Wznosy_hantli_tyłem_leżąc_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Barki_Wznosy_hantli_tyłem_leżąc_3 {
            get {
                object obj = ResourceManager.GetObject("Barki_Wznosy_hantli_tyłem_leżąc_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Barki_Wznosy_hantli_tyłem_leżąc_4 {
            get {
                object obj = ResourceManager.GetObject("Barki_Wznosy_hantli_tyłem_leżąc_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Barki_Wznosy_hantli_tyłem_w_opadzie_tułowia_1 {
            get {
                object obj = ResourceManager.GetObject("Barki_Wznosy_hantli_tyłem_w_opadzie_tułowia_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Barki_Wznosy_hantli_tyłem_w_opadzie_tułowia_2 {
            get {
                object obj = ResourceManager.GetObject("Barki_Wznosy_hantli_tyłem_w_opadzie_tułowia_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Barki_Wznosy_hantli_tyłem_w_opadzie_tułowia_3 {
            get {
                object obj = ResourceManager.GetObject("Barki_Wznosy_hantli_tyłem_w_opadzie_tułowia_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Barki_Wznosy_hantli_tyłem_w_opadzie_tułowia_4 {
            get {
                object obj = ResourceManager.GetObject("Barki_Wznosy_hantli_tyłem_w_opadzie_tułowia_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Brzuch_Deska_bokiem_1 {
            get {
                object obj = ResourceManager.GetObject("Brzuch_Deska_bokiem_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Brzuch_Deska_bokiem_2 {
            get {
                object obj = ResourceManager.GetObject("Brzuch_Deska_bokiem_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Brzuch_Deska_plank_1 {
            get {
                object obj = ResourceManager.GetObject("Brzuch_Deska_plank_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Brzuch_Deska_plank_2 {
            get {
                object obj = ResourceManager.GetObject("Brzuch_Deska_plank_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Brzuch_Deska_plank_3 {
            get {
                object obj = ResourceManager.GetObject("Brzuch_Deska_plank_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Brzuch_Podnoszenie_nóg_wisząc_na_drążku_1 {
            get {
                object obj = ResourceManager.GetObject("Brzuch_Podnoszenie_nóg_wisząc_na_drążku_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Brzuch_Podnoszenie_nóg_wisząc_na_drążku_2 {
            get {
                object obj = ResourceManager.GetObject("Brzuch_Podnoszenie_nóg_wisząc_na_drążku_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Brzuch_Podnoszenie_nóg_wisząc_na_drążku_3 {
            get {
                object obj = ResourceManager.GetObject("Brzuch_Podnoszenie_nóg_wisząc_na_drążku_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Brzuch_Rollowanie_AB_wheel_1 {
            get {
                object obj = ResourceManager.GetObject("Brzuch_Rollowanie_AB_wheel_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Brzuch_Rollowanie_AB_wheel_2 {
            get {
                object obj = ResourceManager.GetObject("Brzuch_Rollowanie_AB_wheel_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Brzuch_Rowerek_w_powietrzu_leżąc_1 {
            get {
                object obj = ResourceManager.GetObject("Brzuch_Rowerek_w_powietrzu_leżąc_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Brzuch_Rowerek_w_powietrzu_leżąc_2 {
            get {
                object obj = ResourceManager.GetObject("Brzuch_Rowerek_w_powietrzu_leżąc_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Brzuch_Rowerek_w_powietrzu_leżąc_3 {
            get {
                object obj = ResourceManager.GetObject("Brzuch_Rowerek_w_powietrzu_leżąc_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Brzuch_Skłony_tułowia_leżąc_1 {
            get {
                object obj = ResourceManager.GetObject("Brzuch_Skłony_tułowia_leżąc_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Brzuch_Skłony_tułowia_leżąc_2 {
            get {
                object obj = ResourceManager.GetObject("Brzuch_Skłony_tułowia_leżąc_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Brzuch_Skrętoskłony_siedząc_russian_twist_1 {
            get {
                object obj = ResourceManager.GetObject("Brzuch_Skrętoskłony_siedząc_russian_twist_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Brzuch_Skrętoskłony_siedząc_russian_twist_2 {
            get {
                object obj = ResourceManager.GetObject("Brzuch_Skrętoskłony_siedząc_russian_twist_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Brzuch_Skrętoskłony_siedząc_russian_twist_3 {
            get {
                object obj = ResourceManager.GetObject("Brzuch_Skrętoskłony_siedząc_russian_twist_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Brzuch_Unoszenie_nóg_leżąc_1 {
            get {
                object obj = ResourceManager.GetObject("Brzuch_Unoszenie_nóg_leżąc_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Brzuch_Unoszenie_nóg_leżąc_2 {
            get {
                object obj = ResourceManager.GetObject("Brzuch_Unoszenie_nóg_leżąc_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Klatka_Przenoszenie_hantla_za_głowę__1 {
            get {
                object obj = ResourceManager.GetObject("Klatka_Przenoszenie_hantla_za_głowę__1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Klatka_Przenoszenie_hantla_za_głowę__2 {
            get {
                object obj = ResourceManager.GetObject("Klatka_Przenoszenie_hantla_za_głowę__2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Klatka_Przenoszenie_hantla_za_głowę__3 {
            get {
                object obj = ResourceManager.GetObject("Klatka_Przenoszenie_hantla_za_głowę__3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Klatka_Przenoszenie_hantla_za_głowę__4 {
            get {
                object obj = ResourceManager.GetObject("Klatka_Przenoszenie_hantla_za_głowę__4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Klatka_Rozpiętki_hantlami_1 {
            get {
                object obj = ResourceManager.GetObject("Klatka_Rozpiętki_hantlami_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Klatka_Rozpiętki_hantlami_2 {
            get {
                object obj = ResourceManager.GetObject("Klatka_Rozpiętki_hantlami_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Klatka_Rozpiętki_hantlami_3 {
            get {
                object obj = ResourceManager.GetObject("Klatka_Rozpiętki_hantlami_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Klatka_Rozpiętki_hantlami_4 {
            get {
                object obj = ResourceManager.GetObject("Klatka_Rozpiętki_hantlami_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Klatka_Rozpiętki_linkami_na_bramie_1 {
            get {
                object obj = ResourceManager.GetObject("Klatka_Rozpiętki_linkami_na_bramie_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Klatka_Rozpiętki_linkami_na_bramie_2 {
            get {
                object obj = ResourceManager.GetObject("Klatka_Rozpiętki_linkami_na_bramie_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Klatka_Rozpiętki_linkami_na_bramie_3 {
            get {
                object obj = ResourceManager.GetObject("Klatka_Rozpiętki_linkami_na_bramie_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Klatka_Rozpiętki_linkami_na_bramie_4 {
            get {
                object obj = ResourceManager.GetObject("Klatka_Rozpiętki_linkami_na_bramie_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Klatka_Wyciskanie_hantli_na_ławce_prostej_1 {
            get {
                object obj = ResourceManager.GetObject("Klatka_Wyciskanie_hantli_na_ławce_prostej_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Klatka_Wyciskanie_hantli_na_ławce_prostej_2 {
            get {
                object obj = ResourceManager.GetObject("Klatka_Wyciskanie_hantli_na_ławce_prostej_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Klatka_Wyciskanie_hantli_na_ławce_skośnej_3 {
            get {
                object obj = ResourceManager.GetObject("Klatka_Wyciskanie_hantli_na_ławce_skośnej_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Klatka_Wyciskanie_hantli_na_ławce_skośnej_4 {
            get {
                object obj = ResourceManager.GetObject("Klatka_Wyciskanie_hantli_na_ławce_skośnej_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Klatka_Wyciskanie_sztangi_na_ławce_płaskiej_1 {
            get {
                object obj = ResourceManager.GetObject("Klatka_Wyciskanie_sztangi_na_ławce_płaskiej_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Klatka_Wyciskanie_sztangi_na_ławce_płaskiej_2 {
            get {
                object obj = ResourceManager.GetObject("Klatka_Wyciskanie_sztangi_na_ławce_płaskiej_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Klatka_Wyciskanie_sztangi_na_ławce_płaskiej_3 {
            get {
                object obj = ResourceManager.GetObject("Klatka_Wyciskanie_sztangi_na_ławce_płaskiej_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Klatka_Wyciskanie_sztangi_na_ławce_płaskiej_4 {
            get {
                object obj = ResourceManager.GetObject("Klatka_Wyciskanie_sztangi_na_ławce_płaskiej_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Klatka_Wyciskanie_sztangi_na_ławce_płaskiej_5 {
            get {
                object obj = ResourceManager.GetObject("Klatka_Wyciskanie_sztangi_na_ławce_płaskiej_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Klatka_Wyciskanie_sztangi_na_ławce_płaskiej_6 {
            get {
                object obj = ResourceManager.GetObject("Klatka_Wyciskanie_sztangi_na_ławce_płaskiej_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Klatka_Wyciskanie_sztangi_na_ławce_skośnej_1 {
            get {
                object obj = ResourceManager.GetObject("Klatka_Wyciskanie_sztangi_na_ławce_skośnej_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Klatka_Wyciskanie_sztangi_na_ławce_skośnej_2 {
            get {
                object obj = ResourceManager.GetObject("Klatka_Wyciskanie_sztangi_na_ławce_skośnej_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Klatka_Wyciskanie_sztangi_na_ławce_skośnej_3 {
            get {
                object obj = ResourceManager.GetObject("Klatka_Wyciskanie_sztangi_na_ławce_skośnej_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap menubackground {
            get {
                object obj = ResourceManager.GetObject("menubackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nogi_Martwy_ciąg_na_prostych_nogach_1 {
            get {
                object obj = ResourceManager.GetObject("Nogi_Martwy_ciąg_na_prostych_nogach_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nogi_Martwy_ciąg_na_prostych_nogach_2 {
            get {
                object obj = ResourceManager.GetObject("Nogi_Martwy_ciąg_na_prostych_nogach_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nogi_Martwy_ciąg_na_prostych_nogach_3 {
            get {
                object obj = ResourceManager.GetObject("Nogi_Martwy_ciąg_na_prostych_nogach_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nogi_Martwy_ciąg_na_prostych_nogach_4 {
            get {
                object obj = ResourceManager.GetObject("Nogi_Martwy_ciąg_na_prostych_nogach_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nogi_Przysiady_ze_sztangą_1 {
            get {
                object obj = ResourceManager.GetObject("Nogi_Przysiady_ze_sztangą_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nogi_Przysiady_ze_sztangą_2 {
            get {
                object obj = ResourceManager.GetObject("Nogi_Przysiady_ze_sztangą_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nogi_Przysiady_ze_sztangą_3 {
            get {
                object obj = ResourceManager.GetObject("Nogi_Przysiady_ze_sztangą_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nogi_Przysiady_ze_sztangą_4 {
            get {
                object obj = ResourceManager.GetObject("Nogi_Przysiady_ze_sztangą_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nogi_Przysiady_ze_sztangą_5 {
            get {
                object obj = ResourceManager.GetObject("Nogi_Przysiady_ze_sztangą_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nogi_Przysiady_ze_sztangą_6 {
            get {
                object obj = ResourceManager.GetObject("Nogi_Przysiady_ze_sztangą_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nogi_Spinanie_łydek_na_maszynie_Smitha_1 {
            get {
                object obj = ResourceManager.GetObject("Nogi_Spinanie_łydek_na_maszynie_Smitha_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nogi_Spinanie_łydek_na_maszynie_Smitha_2 {
            get {
                object obj = ResourceManager.GetObject("Nogi_Spinanie_łydek_na_maszynie_Smitha_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nogi_Spinanie_łydek_na_maszynie_Smitha_3 {
            get {
                object obj = ResourceManager.GetObject("Nogi_Spinanie_łydek_na_maszynie_Smitha_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nogi_Uginanie_nóg_z_hantlem_leżąc_1 {
            get {
                object obj = ResourceManager.GetObject("Nogi_Uginanie_nóg_z_hantlem_leżąc_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nogi_Uginanie_nóg_z_hantlem_leżąc_2 {
            get {
                object obj = ResourceManager.GetObject("Nogi_Uginanie_nóg_z_hantlem_leżąc_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nogi_Unoszenie_bioder_z_obciążeniem_Hip_Thrust_1 {
            get {
                object obj = ResourceManager.GetObject("Nogi_Unoszenie_bioder_z_obciążeniem_Hip_Thrust_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nogi_Unoszenie_bioder_z_obciążeniem_Hip_Thrust_2 {
            get {
                object obj = ResourceManager.GetObject("Nogi_Unoszenie_bioder_z_obciążeniem_Hip_Thrust_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nogi_Unoszenie_bioder_z_obciążeniem_Hip_Thrust_3 {
            get {
                object obj = ResourceManager.GetObject("Nogi_Unoszenie_bioder_z_obciążeniem_Hip_Thrust_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nogi_Unoszenie_bioder_z_obciążeniem_Hip_Thrust_4 {
            get {
                object obj = ResourceManager.GetObject("Nogi_Unoszenie_bioder_z_obciążeniem_Hip_Thrust_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nogi_Wspięcia_na_palce_na_maszynie_1 {
            get {
                object obj = ResourceManager.GetObject("Nogi_Wspięcia_na_palce_na_maszynie_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nogi_Wspięcia_na_palce_na_maszynie_2 {
            get {
                object obj = ResourceManager.GetObject("Nogi_Wspięcia_na_palce_na_maszynie_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nogi_Wyciskanie_na_suwnicy_leżąc_1 {
            get {
                object obj = ResourceManager.GetObject("Nogi_Wyciskanie_na_suwnicy_leżąc_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nogi_Wyciskanie_na_suwnicy_leżąc_2 {
            get {
                object obj = ResourceManager.GetObject("Nogi_Wyciskanie_na_suwnicy_leżąc_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nogi_Wyciskanie_na_suwnicy_leżąc_3 {
            get {
                object obj = ResourceManager.GetObject("Nogi_Wyciskanie_na_suwnicy_leżąc_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nogi_Wyciskanie_na_suwnicy_leżąc_4 {
            get {
                object obj = ResourceManager.GetObject("Nogi_Wyciskanie_na_suwnicy_leżąc_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nogi_Wykroki_1 {
            get {
                object obj = ResourceManager.GetObject("Nogi_Wykroki_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nogi_Wykroki_2 {
            get {
                object obj = ResourceManager.GetObject("Nogi_Wykroki_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nogi_Wykroki_3 {
            get {
                object obj = ResourceManager.GetObject("Nogi_Wykroki_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nogi_Wyprosty_na_maszynie_1 {
            get {
                object obj = ResourceManager.GetObject("Nogi_Wyprosty_na_maszynie_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nogi_Wyprosty_na_maszynie_2 {
            get {
                object obj = ResourceManager.GetObject("Nogi_Wyprosty_na_maszynie_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nogi_Wyprosty_na_maszynie_3 {
            get {
                object obj = ResourceManager.GetObject("Nogi_Wyprosty_na_maszynie_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nogi_Zginanie_nóg_na_maszynie_1 {
            get {
                object obj = ResourceManager.GetObject("Nogi_Zginanie_nóg_na_maszynie_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nogi_Zginanie_nóg_na_maszynie_2 {
            get {
                object obj = ResourceManager.GetObject("Nogi_Zginanie_nóg_na_maszynie_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plecy_Martwy_ciąg_1 {
            get {
                object obj = ResourceManager.GetObject("Plecy_Martwy_ciąg_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plecy_Martwy_ciąg_2 {
            get {
                object obj = ResourceManager.GetObject("Plecy_Martwy_ciąg_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plecy_Martwy_ciąg_3 {
            get {
                object obj = ResourceManager.GetObject("Plecy_Martwy_ciąg_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plecy_Martwy_ciąg_4 {
            get {
                object obj = ResourceManager.GetObject("Plecy_Martwy_ciąg_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plecy_Podciąganie_na_drążku_1 {
            get {
                object obj = ResourceManager.GetObject("Plecy_Podciąganie_na_drążku_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plecy_Podciąganie_na_drążku_2 {
            get {
                object obj = ResourceManager.GetObject("Plecy_Podciąganie_na_drążku_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plecy_Podciąganie_na_drążku_3 {
            get {
                object obj = ResourceManager.GetObject("Plecy_Podciąganie_na_drążku_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plecy_Podciąganie_na_drążku_4 {
            get {
                object obj = ResourceManager.GetObject("Plecy_Podciąganie_na_drążku_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plecy_Ściąganie_drążka_do_klatki_siedząc_1 {
            get {
                object obj = ResourceManager.GetObject("Plecy_Ściąganie_drążka_do_klatki_siedząc_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plecy_Ściąganie_drążka_do_klatki_siedząc_2 {
            get {
                object obj = ResourceManager.GetObject("Plecy_Ściąganie_drążka_do_klatki_siedząc_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plecy_Ściąganie_drążka_do_klatki_siedząc_3 {
            get {
                object obj = ResourceManager.GetObject("Plecy_Ściąganie_drążka_do_klatki_siedząc_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plecy_Ściąganie_drążka_do_klatki_siedząc_4 {
            get {
                object obj = ResourceManager.GetObject("Plecy_Ściąganie_drążka_do_klatki_siedząc_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plecy_Wiosłowanie_na_maszynie_siedząc_1 {
            get {
                object obj = ResourceManager.GetObject("Plecy_Wiosłowanie_na_maszynie_siedząc_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plecy_Wiosłowanie_na_maszynie_siedząc_2 {
            get {
                object obj = ResourceManager.GetObject("Plecy_Wiosłowanie_na_maszynie_siedząc_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plecy_Wiosłowanie_na_maszynie_siedząc_3 {
            get {
                object obj = ResourceManager.GetObject("Plecy_Wiosłowanie_na_maszynie_siedząc_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plecy_Wiosłowanie_na_maszynie_siedząc_4 {
            get {
                object obj = ResourceManager.GetObject("Plecy_Wiosłowanie_na_maszynie_siedząc_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plecy_Wiosłowanie_sztangą_w_opadzie_tułowia_1 {
            get {
                object obj = ResourceManager.GetObject("Plecy_Wiosłowanie_sztangą_w_opadzie_tułowia_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plecy_Wiosłowanie_sztangą_w_opadzie_tułowia_2 {
            get {
                object obj = ResourceManager.GetObject("Plecy_Wiosłowanie_sztangą_w_opadzie_tułowia_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plecy_Wiosłowanie_sztangą_w_opadzie_tułowia_3 {
            get {
                object obj = ResourceManager.GetObject("Plecy_Wiosłowanie_sztangą_w_opadzie_tułowia_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plecy_Wiosłowanie_sztangą_w_opadzie_tułowia_4 {
            get {
                object obj = ResourceManager.GetObject("Plecy_Wiosłowanie_sztangą_w_opadzie_tułowia_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plecy_Wiosłowanie_sztangą_w_opadzie_tułowia_5 {
            get {
                object obj = ResourceManager.GetObject("Plecy_Wiosłowanie_sztangą_w_opadzie_tułowia_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plecy_Wiosłowanie_sztangą_w_opadzie_tułowia_6 {
            get {
                object obj = ResourceManager.GetObject("Plecy_Wiosłowanie_sztangą_w_opadzie_tułowia_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plecy_Wiosłowanie_sztangą_w_opadzie_tułowia_7 {
            get {
                object obj = ResourceManager.GetObject("Plecy_Wiosłowanie_sztangą_w_opadzie_tułowia_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plecy_Wiosłowanie_sztangą_w_opadzie_tułowia_8 {
            get {
                object obj = ResourceManager.GetObject("Plecy_Wiosłowanie_sztangą_w_opadzie_tułowia_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plecy_WiosłowanieHantlem_1 {
            get {
                object obj = ResourceManager.GetObject("Plecy_WiosłowanieHantlem_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plecy_WiosłowanieHantlem_2 {
            get {
                object obj = ResourceManager.GetObject("Plecy_WiosłowanieHantlem_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plecy_WiosłowanieHantlem_3 {
            get {
                object obj = ResourceManager.GetObject("Plecy_WiosłowanieHantlem_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plecy_WiosłowanieHantlem_4 {
            get {
                object obj = ResourceManager.GetObject("Plecy_WiosłowanieHantlem_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plecy_Wznosy_barków_szrugs_1 {
            get {
                object obj = ResourceManager.GetObject("Plecy_Wznosy_barków_szrugs_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plecy_Wznosy_barków_szrugs_2 {
            get {
                object obj = ResourceManager.GetObject("Plecy_Wznosy_barków_szrugs_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ramiona__Uginianie_ramion_na_modlitewniku_1 {
            get {
                object obj = ResourceManager.GetObject("Ramiona__Uginianie_ramion_na_modlitewniku_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ramiona__Uginianie_ramion_na_modlitewniku_2 {
            get {
                object obj = ResourceManager.GetObject("Ramiona__Uginianie_ramion_na_modlitewniku_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ramiona_Pompki_na_poręczach_Dipy_1 {
            get {
                object obj = ResourceManager.GetObject("Ramiona_Pompki_na_poręczach_Dipy_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ramiona_Pompki_na_poręczach_Dipy_2 {
            get {
                object obj = ResourceManager.GetObject("Ramiona_Pompki_na_poręczach_Dipy_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ramiona_Pompki_na_poręczach_Dipy_3 {
            get {
                object obj = ResourceManager.GetObject("Ramiona_Pompki_na_poręczach_Dipy_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ramiona_Pompki_na_poręczach_Dipy_4 {
            get {
                object obj = ResourceManager.GetObject("Ramiona_Pompki_na_poręczach_Dipy_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ramiona_Uginanie_nadgarstka_1 {
            get {
                object obj = ResourceManager.GetObject("Ramiona_Uginanie_nadgarstka_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ramiona_Uginanie_nadgarstka_2 {
            get {
                object obj = ResourceManager.GetObject("Ramiona_Uginanie_nadgarstka_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ramiona_Uginanie_ramion_chwytem_młotkowym_1 {
            get {
                object obj = ResourceManager.GetObject("Ramiona_Uginanie_ramion_chwytem_młotkowym_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ramiona_Uginanie_ramion_chwytem_młotkowym_2 {
            get {
                object obj = ResourceManager.GetObject("Ramiona_Uginanie_ramion_chwytem_młotkowym_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ramiona_Uginanie_ramion_chwytem_młotkowym_3 {
            get {
                object obj = ResourceManager.GetObject("Ramiona_Uginanie_ramion_chwytem_młotkowym_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ramiona_Uginanie_ramion_z_hantlem_1 {
            get {
                object obj = ResourceManager.GetObject("Ramiona_Uginanie_ramion_z_hantlem_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ramiona_Uginanie_ramion_z_hantlem_2 {
            get {
                object obj = ResourceManager.GetObject("Ramiona_Uginanie_ramion_z_hantlem_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ramiona_Uginanie_ramion_z_hantlem_3 {
            get {
                object obj = ResourceManager.GetObject("Ramiona_Uginanie_ramion_z_hantlem_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ramiona_Uginanie_ramion_ze_sztangą_1 {
            get {
                object obj = ResourceManager.GetObject("Ramiona_Uginanie_ramion_ze_sztangą_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ramiona_Uginanie_ramion_ze_sztangą_2 {
            get {
                object obj = ResourceManager.GetObject("Ramiona_Uginanie_ramion_ze_sztangą_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ramiona_Uginianie_ramion_na_wyciągu_dolnym_1 {
            get {
                object obj = ResourceManager.GetObject("Ramiona_Uginianie_ramion_na_wyciągu_dolnym_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ramiona_Uginianie_ramion_na_wyciągu_dolnym_2 {
            get {
                object obj = ResourceManager.GetObject("Ramiona_Uginianie_ramion_na_wyciągu_dolnym_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ramiona_Wiszenie_na_drążku {
            get {
                object obj = ResourceManager.GetObject("Ramiona_Wiszenie_na_drążku", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ramiona_Wyciskanie_francuskie_hantli_1 {
            get {
                object obj = ResourceManager.GetObject("Ramiona_Wyciskanie_francuskie_hantli_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ramiona_Wyciskanie_francuskie_hantli_2 {
            get {
                object obj = ResourceManager.GetObject("Ramiona_Wyciskanie_francuskie_hantli_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ramiona_Wyciskanie_francuskie_hantli_3 {
            get {
                object obj = ResourceManager.GetObject("Ramiona_Wyciskanie_francuskie_hantli_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ramiona_Wyciskanie_francuskie_hantli_4 {
            get {
                object obj = ResourceManager.GetObject("Ramiona_Wyciskanie_francuskie_hantli_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ramiona_Wyciskanie_francuskie_sztangi_1 {
            get {
                object obj = ResourceManager.GetObject("Ramiona_Wyciskanie_francuskie_sztangi_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ramiona_Wyciskanie_francuskie_sztangi_2 {
            get {
                object obj = ResourceManager.GetObject("Ramiona_Wyciskanie_francuskie_sztangi_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ramiona_Wyciskanie_francuskie_sztangi_3 {
            get {
                object obj = ResourceManager.GetObject("Ramiona_Wyciskanie_francuskie_sztangi_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ramiona_Wyciskanie_francuskie_sztangi_4 {
            get {
                object obj = ResourceManager.GetObject("Ramiona_Wyciskanie_francuskie_sztangi_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ramiona_Wyprosty_ramion_na_wyciągu_dolnym_1 {
            get {
                object obj = ResourceManager.GetObject("Ramiona_Wyprosty_ramion_na_wyciągu_dolnym_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ramiona_Wyprosty_ramion_na_wyciągu_dolnym_2 {
            get {
                object obj = ResourceManager.GetObject("Ramiona_Wyprosty_ramion_na_wyciągu_dolnym_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ramiona_Wyprosty_ramion_na_wyciągu_górnym_3 {
            get {
                object obj = ResourceManager.GetObject("Ramiona_Wyprosty_ramion_na_wyciągu_górnym_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ramiona_Wyprosty_ramion_na_wyciągu_górnym_4 {
            get {
                object obj = ResourceManager.GetObject("Ramiona_Wyprosty_ramion_na_wyciągu_górnym_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ramiona_Wyprosty_ramion_z_hantlem_zza_głowy_1 {
            get {
                object obj = ResourceManager.GetObject("Ramiona_Wyprosty_ramion_z_hantlem_zza_głowy_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ramiona_Wyprosty_ramion_z_hantlem_zza_głowy_2 {
            get {
                object obj = ResourceManager.GetObject("Ramiona_Wyprosty_ramion_z_hantlem_zza_głowy_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ramiona_Wyprosty_ramion_z_hantlem_zza_głowy_3 {
            get {
                object obj = ResourceManager.GetObject("Ramiona_Wyprosty_ramion_z_hantlem_zza_głowy_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ramiona_Wyprosty_ramion_z_hantlem_zza_głowy_4 {
            get {
                object obj = ResourceManager.GetObject("Ramiona_Wyprosty_ramion_z_hantlem_zza_głowy_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
